### ISSUE TITLE
Allow checkConsent to also be synchronous

### ISSUE THREAD

**Issue by NickM-27** [igormatyushkin014/Consent#1]
There are times when one might want to check that certain permissions are active and need to do so synchronously

**Comment by igormatyushkin014** [comment]
@NickM-27 Actually, `checkConsent()` works synchronously. Lambda expression was added for the uniform API syntax with `request().whenFinished {}`. Anyway, I see lambda expression may be confusing so it's a good idea to implement more obvious way to get the result synchronously.

**Comment by ghost** [comment]
@NickM-27 Actually, `checkConsent()` works synchronously. Lambda expression was added for the uniform API syntax with `getConsent().whenFinished {}`. Anyway, I see lambda expression may be confusing so it's a good idea to implement more obvious way to get the result synchronously.

**Comment by ghost** [comment]
@NickM-27, [documentation](https://github.com/igormatyushkin014/Consent#check-permissions) is updated. Use version `1.1`:

```javascript
dependencies {
    implementation 'com.github.igormatyushkin014:Consent:1.1'
}
```

**Comment by NickM-27** [comment]
Awesome! Thanks and great work
