### ISSUE TITLE
Add Context extension for checkConsent

### ISSUE THREAD

**Issue by NickM-27** [igormatyushkin014/Consent#2]
While you need an Activity to request a permission, it can still be useful to check if a permission is granted from a broadcast receiver or service.

**Comment by ghost** [comment]
@NickM-27, your commits ba53a8852569f345a3334187a5e142e3ec71b274 and feac10c99c76e4e72554c4449038ec6beb786d49 are included in the version `1.1`

Thanks for contributing! I really appreciate it.

**Comment by NickM-27** [comment]
No problem, happy to help as I already have this in two of my apps!
